# Generated by Django 5.2.4 on 2025-10-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_teacherprofile_class_level_alter_result_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_eo',
            field=models.BooleanField(default=False, help_text='Check if this user is an Examination Officer (EO)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='result',
            name='term',
            field=models.CharField(choices=[('1', 'First Term'), ('2', 'Second Term'), ('3', 'Third Term')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.CharField(choices=[('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], default='SS1', max_length=3),
        ),
    ]
