# Generated by Django 5.2.4 on 2025-10-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_teacherprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
    ]
