# Generated by Django 5.2.4 on 2025-10-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_remove_teacherprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
